import type { ComponentType } from 'react';
import {
  Activity,
  ArrowLeft,
  ArrowUpRight,
  Ban,
  BookOpenText,
  Box,
  Brain,
  Coins,
  CreditCard,
  DollarSign,
  FileText,
  Folder,
  Github,
  HelpCircle,
  Home,
  Image,
  Key,
  Layers,
  Mail,
  Menu,
  MessageCircle,
  Newspaper,
  Pencil,
  Plus,
  Search,
  Settings,
  ShieldCheck,
  Sparkles,
  User,
  Users,
  Wand,
  Zap,
} from 'lucide-react';
import {
  RiAddLine,
  RiAspectRatioLine,
  RiBankCardLine,
  RiBarChart2Line,
  RiChat2Line,
  RiClapperboardAiLine,
  RiCloudy2Fill,
  RiCloudyFill,
  RiCodeFill,
  RiDatabase2Line,
  RiDeleteBinLine,
  RiDiscordFill,
  RiEditLine,
  RiEyeLine,
  RiFlashlightLine,
  RiFocus2Line,
  RiImage2Line,
  RiKey2Fill,
  RiKeyLine,
  RiLandscapeLine,
  RiLayout4Line,
  RiLockPasswordLine,
  RiMagicLine,
  RiMessage2Line,
  RiMusic2Line,
  RiNextjsFill,
  RiQuestionLine,
  RiRefreshLine,
  RiRobot2Line,
  RiRocket2Line,
  RiSettings4Line,
  RiStackLine,
  RiTaskLine,
  RiTwitterXFill,
  RiUserStarLine,
  RiVideoLine,
} from 'react-icons/ri';

const iconRegistry: Record<string, ComponentType<any>> = {
  Activity,
  ArrowLeft,
  ArrowUpRight,
  Ban,
  BookOpenText,
  Box,
  Brain,
  Coins,
  CreditCard,
  DollarSign,
  FileText,
  Folder,
  Github,
  HelpCircle,
  Home,
  Image,
  Key,
  Layers,
  Mail,
  Menu,
  message: MessageCircle,
  MessageCircle,
  Newspaper,
  Pencil,
  Plus,
  Search,
  Settings,
  ShieldCheck,
  Sparkles,
  User,
  Users,
  Wand,
  Zap,
  RiAddLine,
  RiAspectRatioLine,
  RiBankCardLine,
  RiBarChart2Line,
  RiChat2Line,
  RiClapperboardAiLine,
  RiCloudy2Fill,
  RiCloudyFill,
  RiCodeFill,
  RiDatabase2Line,
  RiDeleteBinLine,
  RiDiscordFill,
  RiEditLine,
  RiEyeLine,
  RiFlashlightLine,
  RiFocus2Line,
  RiImage2Line,
  RiKey2Fill,
  RiKeyLine,
  RiLandscapeLine,
  RiLayout4Line,
  RiLockPasswordLine,
  RiMagicLine,
  RiMessage2Line,
  RiMusic2Line,
  RiNextjsFill,
  RiRefreshLine,
  RiRobot2Line,
  RiRocket2Line,
  RiSettings4Line,
  RiStackLine,
  RiTaskLine,
  RiTwitterXFill,
  RiUserStarLine,
  RiVideoLine,
};

export function SmartIcon({
  name,
  size = 24,
  className,
  ...props
}: {
  name: string;
  size?: number;
  className?: string;
  [key: string]: any;
}) {
  const IconComponent =
    iconRegistry[name] || (name?.startsWith('Ri') ? RiQuestionLine : HelpCircle);

  return <IconComponent size={size} className={className} {...props} />;
}
